### ISSUE TITLE
Sensor not available

### ISSUE THREAD

**Issue by murmelbahn** [custom-components/sensor.stadtreinigung_hamburg#13]
Hi,

since 04.08.22 my sensors are not available anymore.
Maybe the Stadtreinigung changed something on their side?
Does someone have the same error?
Sadly I don't know how to help further.

**Comment by fabsenet** [comment]
Hi, yes it is the same for me. So it looks like we have to investigate?

**Comment by vigonotion** [comment]
Please try version 1.1.1, it works for me now
