### ISSUE TITLE
No assets found for release 'tags/v1.1.2'

### ISSUE THREAD

**Issue by oliverboermel** [custom-components/sensor.stadtreinigung_hamburg#17]
During Installation
I have these on 2 HA installtion both Pi4 with ssd current Version tryed already reboot
Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:899
Integration: HACS ([documentation](https://hacs.xyz/docs/configuration/start), [issues](https://github.com/hacs/integration/issues))
First occurred: 8:09:54 AM (2 occurrences)
Last logged: 8:11:39 AM

<Integration custom-components/sensor.stadtreinigung_hamburg> No assets found for release 'tags/v1.1.2'

**Comment by svenstaro** [comment]
@vigonotion I think you forgot to upload `stadtreinigung_hamburg.zip`.

**Comment by vigonotion** [comment]
fixed in 1.1.3
