### ISSUE TITLE
Deprecation DEVICE_CLASS_TIMESTAMP from HA Core 2025.1

### ISSUE THREAD

**Issue by PhilippBaumgarten** [custom-components/sensor.stadtreinigung_hamburg#18]
## Version of the custom_component
v1.1.3

## Configuration
Standard config

## Describe the bug
There will be a change in the sensor device class from HA Core 2025.1 onwards - so enough time and not yet a bug affecting the system. 

## Debug log
DEVICE_CLASS_TIMESTAMP was used from stadtreinigung_hamburg, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.TIMESTAMP instead, please report it to the author of the 'stadtreinigung_hamburg' custom integration

**Comment by NordFreak** [comment]
Detected code that calls async_forward_entry_setup for integration stadtreinigung_hamburg with title: Homebase and entry_id: x, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by vigonotion** [comment]
fixed in the latest release

thanks for reporting and thanks @040medien  for fixing this!

@NordFreak your issue seems to be fixed by #19
