### ISSUE TITLE
Error importing platform config_flow

### ISSUE THREAD

**Issue by KlaraJa** [custom-components/sensor.stadtreinigung_hamburg#20]
## Version of the custom_component
1.1.3

## Configuration

```yaml

Not needed

```

## Describe the bug
After upgrading HomeAssistant to 2024.10.0 the Integration does not start anymore and throws an error.

## Debug log

```text

Logger: homeassistant.config_entries
Source: config_entries.py:563
First occurred: 20:56:36 (2 occurrences)
Last logged: 22:11:29

Error importing platform config_flow from integration stadtreinigung_hamburg to set up stadtreinigung_hamburg configuration entry: lxml.html.clean module is now a separate project lxml_html_clean. Install lxml[html_clean] or lxml_html_clean directly.

```

**Comment by NordFreak** [comment]
Here the same: 

Logger: homeassistant.config_entries
Quelle: config_entries.py:563
Erstmals aufgetreten: 06:03:52 (2 Vorkommnisse)
Zuletzt protokolliert: 12:49:22

Error importing platform config_flow from integration stadtreinigung_hamburg to set up stadtreinigung_hamburg configuration entry: lxml.html.clean module is now a separate project lxml_html_clean. Install lxml[html_clean] or lxml_html_clean directly.

**Comment by murmelbahn** [comment]
Yeah, I've the same error. Would be really nice if you can fix this.

**Comment by quackelduck** [comment]
Error here as well. Here are the error-protocols from my side:

> Logger: py.warnings
> Quelle: custom_components/stadtreinigung_hamburg/config_flow.py:7
> Integration: Stadtreinigung Hamburg ([Dokumentation](https://github.com/custom-> components/sensor.stadtreinigung_hamburg))
> Erstmals aufgetreten: 21:02:10 (3 Vorkommnisse)
> Zuletzt protokolliert: 21:02:10

> /usr/local/lib/python3.12/site-packages/pyppeteer/us_keyboard_layout.py:73: SyntaxWarning: invalid escape sequence '\> (' 'Digit9': {'keyCode': 57, 'code': 'Digit9', 'shiftKey': '\(', 'key': '9'},
> /usr/local/lib/python3.12/site-packages/pyppeteer/us_keyboard_layout.py:143: SyntaxWarning: invalid escape sequence > '\<' 'Comma': {'keyCode': 188, 'code': 'Comma', 'shiftKey': '\<', 'key': ','},
> /usr/local/lib/python3.12/site-packages/pyppeteer/us_keyboard_layout.py:247: SyntaxWarning: invalid escape sequence > '\<' '<': {'keyCode': 188, 'key': '\<', 'code': 'Comma'},

> Logger:` homeassistant.config_entries
> Quelle: config_entries.py:563
> Erstmals aufgetreten: 21:02:18 (1 Vorkommnisse)
> Zuletzt protokolliert: 21:02:18
> 
> Error importing platform config_flow from integration stadtreinigung_hamburg to set up stadtreinigung_hamburg > configuration entry: lxml.html.clean module is now a separate project lxml_html_clean. Install lxml[html_clean] or > lxml_html_clean directly.

>Logger: homeassistant.util.loop
Quelle: util/loop.py:77
Erstmals aufgetreten: 21:02:18 (2 Vorkommnisse)
Zuletzt protokolliert: 21:02:18

Detected blocking call to import_module with args ('custom_components.stadtreinigung_hamburg.config_flow',) in /usr/src/homeassistant/homeassistant/loader.py, line 1296: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 561, in async_setup await integration.async_get_platform("config_flow") File "/usr/src/homeassistant/homeassistant/loader.py", line 1100, in async_get_platform platforms = await self.async_get_platforms((platform_name,)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms platforms.update(self._load_platforms(platform_names)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms platform_name: self._load_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}")
Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f6accbc50>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) in /usr/local/lib/python3.12/ssl.py, line 713: context.load_default_certs(purpose) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/gardena/smart_system.py", line 190, in start_ws await self.__launch_websocket_loop(ws_url) File "/usr/local/lib/python3.12/site-packages/gardena/smart_system.py", line 227, in __launch_websocket_loop websocket = await websockets.connect(url, ping_interval=150) File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 654, in __await_impl__ _transport, protocol = await self._create_connection() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1149, in create_connection transport, protocol = await self._create_connection_transport( File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1173, in _create_connection_transport transport = self._make_ssl_transport( File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 83, in _make_ssl_transport ssl_protocol = sslproto.SSLProtocol( File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 295, in __init__ sslcontext = _create_transport_context( File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 55, in _create_transport_context sslcontext = ssl.create_default_context() File "/usr/local/lib/python3.12/ssl.py", line 713, in create_default_context context.load_default_certs(purpose)

**Comment by quackelduck** [comment]
Exactly the same here.

`Error importing platform config_flow from integration stadtreinigung_hamburg to set up stadtreinigung_hamburg configuration entry: lxml.html.clean module is now a separate project lxml_html_clean. Install lxml[html_clean] or lxml_html_clean directly.
`

I would really appreciate a fix. Thanks so much!!

**Comment by webmediart-github** [comment]
Same with 2024.10.2
```
Logger: homeassistant.config_entries
Source: config_entries.py:563
First occurred: 21:05:58 (3 occurrences)
Last logged: 21:21:22

Error importing platform config_flow from integration stadtreinigung_hamburg to set up stadtreinigung_hamburg configuration entry: lxml.html.clean module is now a separate project lxml_html_clean. Install lxml[html_clean] or lxml_html_clean directly.
```

**Comment by williknow** [comment]
I am afraid the maintainer is not living in Hamburg anymore. Nothing going on here since last year. Is someone able to take over?
Do we have to switch over to waste collection schedule?

**Comment by pinnbert23** [comment]
you have to add a line ( "lxml_html_clean") to the manifest.json and restart HA! After that it works perfectly!

 Here is the customized code for the manifest.json

{
    "codeowners": [
        "@vigonotion"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/custom-components/sensor.stadtreinigung_hamburg",
    "domain": "stadtreinigung_hamburg",
    "name": "City Cleaning Hamburg",
    "requirements": [
        "city cleaning-hamburg==0.3.1",
        "lxml_html_clean"
    ],
    "version": "v1.1.3"
}

**Comment by quackelduck** [comment]
Works like a charm, thanks!!

**Comment by williknow** [comment]
Thanks for the solution. Do we have some security issues now?

**Comment by NordFreak** [comment]
@040medien 

Hey thanks for your work!
If I'm interpreting your nickname correctly, you're from Hamburg. Thanks for your support from Schnelsen. Since the bug took longer, I switched to Waste Collection. 

Will you now take over the maintenance of the integration permanently? Or do I prefer to stay with Waste Collection?

**Comment by pinnbert23** [comment]
Hello from Winterhude, we can happily continue this together. I think this
addon is better than waste collection. Best regards

NordFreak ***@***.***> schrieb am Fr., 25. Okt. 2024, 10:04:

**Comment by 040medien** [comment]
Hi @NordFreak , @pinnbert23. I only raised a simple PR, which got merged by @vigonotion - I presume he is and will continue to be the maintainer of this repository.

**Comment by vigonotion** [comment]
Hi, I just don't have the time to look at issues and fix them, but I will look at PRs and will release new versions as needed

**Comment by pinnbert23** [comment]
So let us as citizens of Hamburg pay attention to our garbage application

Tom Schneider ***@***.***> schrieb am Fr., 25. Okt. 2024,
20:17:

**Comment by MartinF-HH** [comment]
Hi, let me start by thanking all of you to keep Stadtreinigung working.

I see the following warning in my log. Is that an issue that needs attention and if yes, would you be willing to look at it as well?

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:155
First occurred: 6:29:57 AM (1 occurrences)
Last logged: 6:29:57 AM

Detected code that calls async_forward_entry_setup for integration stadtreinigung_hamburg with title: Frahm and entry_id: 01JAMRXZDMKXGKJ791F4MZ7W2T, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by 040medien** [comment]
@MartinF-HH I'm not an expert, bu this is a separate issue (and as per the error this means that in 3 months, this addon will stop working again). Please open a separate issue for this.

**Comment by vigonotion** [comment]
fixed in the latest release

**Comment by svenstaro** [comment]
I'm once again getting
```
Dec 12 09:43:47 morpheus podman[501128]: 2024-12-12 09:43:47.631 WARNING (ImportExecutor_0) [homeassistant.core] Config was used from stadtreinigung_hamburg, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'stadtreinigung_hamburg' custom integration
Dec 12 09:43:47 morpheus podman[501128]: 2024-12-12 09:43:47.631 INFO (SyncWorker_6) [homeassistant.util.package] Attempting install of hass-web-proxy-lib==0.0.7
Dec 12 09:43:47 morpheus podman[501128]: 2024-12-12 09:43:47.633 INFO (MainThread) [homeassistant.setup] Setting up stadtreinigung_hamburg
Dec 12 09:43:47 morpheus podman[501128]: 2024-12-12 09:43:47.633 INFO (MainThread) [homeassistant.setup] Setup of domain stadtreinigung_hamburg took 0.00 seconds
Dec 12 09:43:47 morpheus podman[501128]: 2024-12-12 09:43:47.633 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration stadtreinigung_hamburg to set up stadtreinigung_hamburg configuration entry: Platform stadtreinigung_hamburg.config_flow not found
```
in Home Assistant 2024.12. Not sure what exactly is wrong, though.
