### ISSUE TITLE
Address not available (Building Number)

### ISSUE THREAD

**Issue by andrehamburg** [custom-components/sensor.stadtreinigung_hamburg#26]
Hi, the integration works well, but the data looks not up to date. My address is not available. Why? There are only building numbers with one digit. Please look at the screenshot.

![grafik](https://github.com/user-attachments/assets/50a3801b-f4d4-4f4c-8394-3a204ee28846)

When i check it at the Stadtreinigung Website, my address is available there

![grafik](https://github.com/user-attachments/assets/338ccbb6-8697-4ddd-a389-365d870c5652)

I think my logfiles and configuration are not necessary.

Can you check it please?

Sincerely

André

**Comment by vigonotion** [comment]
Hi, generally, double digits numbers do work. I can take a look at it, but you blurred out your address, you can ping me up on discord (vigonotion) if that would work for you.

**Comment by andrehamburg** [comment]
Hi Vigonotion,
thank you for trying to help me! You've got mail. ;-)
André

**Comment by vigonotion** [comment]
> Hi Vigonotion,
> 
> thank you for trying to help me! You've got mail. ;-)
> 
> André

I didn't receive anything, did you use `tom@sutomaji.net`?

**Comment by andrehamburg** [comment]
I used your vigonotion address and i did'nt received a failure notice until now. I send it again to sutomaji.

**Comment by vigonotion** [comment]
fixed in latest version
