### ISSUE TITLE
Hi is it possible to get a littlebit mor information about the configuration

### ISSUE THREAD

**Issue by ollimagic** [custom-components/sensor.stadtreinigung_hamburg#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ollimagic** [comment]
I try to make it work but honestly i don't know how do i get the Information for my Part
of Hamburg. Maybe you could put an example.

**Comment by vigonotion** [comment]
Please specify what you already tried:
- Did you achieve installing the custom component (does it appear in the Integrations page in Home Assistant)?
- Did you try to enter your address and street number? What did it say (maybe provide a screenshot?)

The integration popup itself _should_ provide you with all the information, but I'm happy to explain it more if I know where you are stuck

**Comment by ollimagic** [comment]
Ok now i understand i did not see  that it appears in the integration.
now is working.
thank you
regards
Oliver

Am Di., 19. Nov. 2019 um 14:54 Uhr schrieb Tom Schneider <
notifications@github.com>:
