### ISSUE TITLE
Date shows "Invalid Date" on iOS, but it's properly displayed in Chrome/DD (desktop)

### ISSUE THREAD

**Issue by monkeydriven** [custom-components/sensor.stadtreinigung_hamburg#4]
Moin! ;)

If I use the sensors that are created through the integration they work fine in Chrome and Firefox (desktop browser). 

![Unbenannt](https://user-images.githubusercontent.com/46463440/77749975-3f83f400-7023-11ea-9290-3f8f1db15b04.JPG)

But in Safari (iOS) it is calculated as an invalid date.

![grafik](https://user-images.githubusercontent.com/46463440/77750168-9f7a9a80-7023-11ea-95a5-d5179f8cd104.png)

According to https://github.com/home-assistant/frontend/issues/4110 this has to do with the timestamp format. 

"
Chrome on Mac and Windows is perfectly happy with the format YYYY-MM-DD HH:MM:SSTZD (as with the value "2019-10-23 09:51:00+03:00") but Safari and Chrome on iOS requires it to be in the format YYYY-MM-DDTHH:MM:SSTZD (e.g. "2019-10-23T09:51:00+03:00")
"

Can you adapt to this ?

**Comment by vigonotion** [comment]
Sure, can you please test this branch: [vi/isotimestamp](https://github.com/custom-components/sensor.stadtreinigung_hamburg/tree/vi/isotimestamp)
I don't have an iOS device to test with, but it still works in Chrome/Firefox and shows the "T" in the timestamp

**Comment by monkeydriven** [comment]
That was fast :) It now works perfectly on iOS as well!
