### ISSUE TITLE
Configuration setup for hacs_waste_collection_schedule

### ISSUE THREAD

**Issue by Liese2007** [custom-components/sensor.stadtreinigung_hamburg#7]
**Is your feature request related to a problem? Please describe.**
The component waste-collection-schedule is mentioning the availability of SRH compatibility.
I have real problems setting up the waste-collection-schedule.

**Describe the solution you'd like**
It seems for me, that for the interface between sensor.stadtreinigung and waste-collection-schedule several arguments are required. 
A description of this interface is required.
A configuration example would nice.

Regards,
Joerg

**Comment by vigonotion** [comment]
I don't understand your issue. Did you follow the [installation guide](https://github.com/custom-components/sensor.stadtreinigung_hamburg#installation) for **this** integration? I never tried waste-collection-schedule, but this integration should be easier to set up using the GUI (just provide a name, your street and street number, no need to fiddle around with ids)

**Comment by Liese2007** [comment]
You are right.
It is more like missing the config info for that other component.
I am wrong here. Your integartion was easy to setup, thanks!
