### ISSUE TITLE
Mismatching information on website and integration

### ISSUE THREAD

**Issue by Liese2007** [custom-components/sensor.stadtreinigung_hamburg#8]
Hi,I checked the 'Garbage Removal Calendar' for our address @ https://www.stadtreinigung.hamburg/privatkunden/abfuhrkalender/index.html#abfuhrkalenderIt shows for next Wednesday Christmas tree removal only,while your sensor is showing Christmas tree AND Bio removal.I thought it is the same database?Can you clarify please how that works?RegardsJoerg

**Comment by vigonotion** [comment]
Can you please provide more information? Screenshots of both the home assistant sensors and the Stadtreinigung hamburg homepage. The address you look up would also be helpful. If you don't want to post this sensitive data here, you can send me a message on Discord at vigonotion#0360

**Comment by Liese2007** [comment]
Jepp, I will send screens via Discord if I figure out how that works.
I 'asked for friendship' as a first step- hope that's ok.

Guten Rutsch! :-)

**Comment by vigonotion** [comment]
This seems to have been bad timing, the web site also shows the same data as Home Assistant now.

The integration works like a web browser and visits the website and extracts the data, so the data should be the same.
