### ISSUE TITLE
„Unknown error occured“ when adding integration and entering address

### ISSUE THREAD

**Issue by pmunck86** [custom-components/sensor.stadtreinigung_hamburg#9]
Hi, i have just found the Integration. After installing i want to add the integration and should enter „Name“, „Strasse“ and „Hausnummer“. When trying to submit unknown error occurs. I‘m on core-2021.4.3

**Comment by vigonotion** [comment]
Thanks for reporting this! I will publish a new version now which fixes this bug.

**Comment by pmunck86** [comment]
Thanks for the quick fix! Working fine now

**Comment by Japander** [comment]
Having the same issue right now
